config/routes.rb
Rails.application.routes.draw do

  #
  # Public
  #

  get '/soon', to: 'holding_pages#show', as: 'holding_page'

  root to: "home#index"

  # Recipes
  resources :recipes
  post '/recipes/save/:id', to: 'recipes#save_to_box', as: 'save_to_box'
  # get 'recipes', to: 'recipes#index', as: 'recipes'
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'

  # Users
  get   '/users', to: 'users#index', as: 'users'
  get   '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  get   '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  get   '/users/:id/recipes/edit', to: 'users#edit_recipes', as: 'edit_user_recipes'
  get   '/users/:id/saved-recipes/edit', to: 'users#edit_saved_recipes', as: 'edit_user_saved_recipes'

  # Blog / Tumblr feed
  get '/mmmbox', to: 'blog#mmmbox', as: 'tumblr'

  # About
  get '/about', to: 'about#index'
  get '/about/statement', to: 'about#statement'

  # Search
  get 'search', to: 'search#index'


  #
  # Admin
  #

  # Admin dashboard
  get '/admin', to: 'dashboard#index', as: 'admin'
  namespace :admin do
    resources :color_schemes
    resources :jewels
    resources :user_groups
    resources :users
  end


  #
  # Authentication
  #

  get '/signup/confirm/:id', to: 'users#confirm', as: 'confirm_user_registration'
  patch '/signup/confirm/:id', to: 'users#confirm_update'

  devise_for :users, path: '', controllers: { registrations: 'users/registrations' },
                               path_names:  { sign_in: '/login', sign_out: '/logout', sign_up: '/signup' }
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

end

app/models/color_scheme.rb
class ColorScheme < ActiveRecord::Base
  has_many :recipes
end

app/controllers/admin/color_schemes_controller.rb
class Admin::ColorSchemesController < Admin::ApplicationController
  before_action :set_color_scheme, only: [:show, :edit, :update, :destroy]

  # GET /admin/color_schemes
  # GET /admin/color_schemes.json
  def index
    @color_schemes = ColorScheme.all
  end

  # GET /admin/color_schemes/1
  # GET /admin/color_schemes/1.json
  def show
  end

  # GET /admin/color_schemes/new
  def new
    @color_scheme = ColorScheme.new
  end

  # GET /admin/color_schemes/1/edit
  def edit
  end

  # POST /admin/color_schemes
  # POST /admin/color_schemes.json
  def create
    @color_scheme = ColorScheme.new(color_scheme_params)

    respond_to do |format|
      if @color_scheme.save
        format.html { redirect_to [:admin, @color_scheme], notice: 'Color scheme was successfully created.' }
        format.json { render action: 'show', status: :created, location: @color_scheme }
      else
        format.html { render action: 'new' }
        format.json { render json: @color_scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/color_schemes/1
  # PATCH/PUT /admin/color_schemes/1.json
  def update
    respond_to do |format|
      if @color_scheme.update(color_scheme_params)
        format.html { redirect_to [:admin, @color_scheme], notice: 'Color scheme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @color_scheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/color_schemes/1
  # DELETE /admin/color_schemes/1.json
  def destroy
    @color_scheme.destroy
    respond_to do |format|
      format.html { redirect_to admin_color_schemes_url, notice: 'Color scheme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color_scheme
      @color_scheme = ColorScheme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_scheme_params
      params.require(:color_scheme).permit(:title, :color)
    end
end

app/helpers/admin/color_schemes_helper.rb
module Admin::ColorSchemesHelper
end

app/views/admin/color_schemes/_form.html.erb
<%= simple_form_for([:admin, @color_scheme]) do |f| %>
  <%= render 'admin/errors', f: f, record: @color_scheme %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :color %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/color_schemes/edit.html.erb
<h1>Editing color_scheme</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @color_scheme] %> |
<%= link_to 'Back', admin_color_schemes_path %>

app/views/admin/color_schemes/index.html.erb
<h1>Listing color_schemes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @color_schemes.each do |color_scheme| %>
      <tr>
        <td><%= color_scheme.title %></td>
        <td><%= color_scheme.color %></td>
        <td><%= link_to 'Show', [:admin, color_scheme] %></td>
        <td><%= link_to 'Edit', edit_admin_color_scheme_path(color_scheme) %></td>
        <td><%= link_to 'Destroy', [:admin, color_scheme], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Color scheme', new_admin_color_scheme_path %>

app/views/admin/color_schemes/new.html.erb
<h1>New color_scheme</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_color_schemes_path %>

app/views/admin/color_schemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @color_scheme.title %>
</p>

<p>
  <strong>Color:</strong>
  <%= @color_scheme.color %>
</p>

<%= link_to 'Edit', edit_admin_color_scheme_path(@color_scheme) %> |
<%= link_to 'Back', admin_color_schemes_path %>