config/routes.rb
Rails.application.routes.draw do

  #
  # Public
  #

  get '/soon', to: 'holding_pages#show', as: 'holding_page'

  root to: "home#index"

  # Recipes
  resources :recipes
  post '/recipes/save/:id', to: 'recipes#save_to_box', as: 'save_to_box'
  # get 'recipes', to: 'recipes#index', as: 'recipes'
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'

  # Users
  get   '/users', to: 'users#index', as: 'users'
  get   '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  get   '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  get   '/users/:id/recipes/edit', to: 'users#edit_recipes', as: 'edit_user_recipes'
  get   '/users/:id/saved-recipes/edit', to: 'users#edit_saved_recipes', as: 'edit_user_saved_recipes'

  # Blog / Tumblr feed
  get '/mmmbox', to: 'blog#mmmbox', as: 'tumblr'

  # About
  get '/about', to: 'about#index'
  get '/about/statement', to: 'about#statement'

  # Search
  get 'search', to: 'search#index'


  #
  # Admin
  #

  # Admin dashboard
  get '/admin', to: 'dashboard#index', as: 'admin'
  namespace :admin do
    resources :color_schemes
    resources :jewels
    resources :user_groups
    resources :users
  end


  #
  # Authentication
  #

  get '/signup/confirm/:id', to: 'users#confirm', as: 'confirm_user_registration'
  patch '/signup/confirm/:id', to: 'users#confirm_update'

  devise_for :users, path: '', controllers: { registrations: 'users/registrations' },
                               path_names:  { sign_in: '/login', sign_out: '/logout', sign_up: '/signup' }
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  # PgSearch
  include PgSearch
  pg_search_scope(
    :search,
    against: {
      title: 'A',
      description: 'B',
    },
    using: {
      tsearch: {
        dictionary: 'english',
      }
    }
  )

  # FriendlyId
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :featured_image,
    styles: {
      sm: '768>',
      md: '992>',
      lg: '1170>',
      xl: '2000>',
    }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/

  enum preparation_time: { quick: 0, time_consuming: 1 }

  after_save :touch!

  validates :title, :description, presence: true

  belongs_to :user
  belongs_to :jewel
  belongs_to :color_scheme

  has_many :steps, -> { order('position') }
  has_many :ingredients, -> { order('position') }

  accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  has_and_belongs_to_many :boxes
  has_and_belongs_to_many :cuisines
  has_and_belongs_to_many :meal_types
  has_and_belongs_to_many :diets
  has_and_belongs_to_many :seasons
  has_and_belongs_to_many :occasions
  has_and_belongs_to_many :pairings,
              class_name: 'Recipe',
              join_table: :pairings_recipes,
              foreign_key: :recipe_id,
              association_foreign_key: :pairing_id

  scope :updated_at_desc, -> { order(updated_at: :desc) }
  scope :random,          -> { order('random()') }
  scope :collected,       -> { joins(:boxes).where('boxes.id IS NOT NULL').distinct }
  scope :not_collected,   -> { includes(:boxes).where( boxes: { id: nil } ) }
  scope :uploaded_by,     -> (user_id) { joins(:user).where('recipes.user_id = ?', user_id) }
  scope :collected_by,    -> (user_id) { joins(:boxes).where('boxes.user_id = ?', user_id) }
  scope :all_except,      -> (recipe) { where.not(id: recipe) }
  scope :with_image,      -> { where.not(featured_image_file_name: [nil, '']) }

  # FriendlyId
  def should_generate_new_friendly_id?
    title_changed?
  end

  def color
    (color_scheme.color if color_scheme) || '#000000'
  end

  def diet_names
    diets.collect { |d| d.title }.to_sentence
  end

  def collected?
    boxes.any?
  end

  private

    def touch!
      self.touch
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :save_to_box, :edit, :update, :destroy]

  def index
    @recipes = Recipe.includes(:user).updated_at_desc
  end

  def show
    @recipe   = Recipe.friendly.find(params[:id])
    @pairings = @recipe.pairings.random
    @user     = @recipe.user
  end

  def save_to_box
    authorize @recipe
    @user = current_or_guest_user

    respond_to do |format|
      if @user.box.recipes.include?(@recipe)
        flash.now[:notice] = 'This recipe is already in your box.'
        format.js { render 'shared/flash_messages' }
      elsif @recipe.user == @user
        flash.now[:notice] = 'This recipe belongs to you; you can\'t add it to your box.'
        format.js { render 'shared/flash_messages' }
      else
        @user.box.recipes << @recipe
      end

      if @user.save
        flash.now[:success] = 'Recipe was added to your box.'
        format.js { render 'shared/flash_messages' }
      else
        flash.now[:error] = 'There was a problem adding this recipe to your box.'
        format.js { render 'shared/flash_messages' }
      end
    end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    authorize @recipe
  end

  # GET /recipes/1/edit
  def edit
    authorize @recipe
    @pairings = @recipe.pairings.random
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    authorize @recipe
    @recipe.user = current_user if current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    authorize @recipe

    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    authorize @recipe

    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_recipe
      @recipe = Recipe.friendly.find(params[:id])
    end

    def user_not_authorized(exception)
      # policy_name = exception.policy.class.to_s.underscore

      # TODO: Redirect to sign up page
      flash.now[:error] = "You must #{view_context.link_to('sign in', new_user_session_path, class: 'link')} before you can add a recipe to your box."
      respond_to do |format|
        format.html { redirect_to @recipe, flash: {
          error: not_authorized_to_edit_flash_error }
        }
        format.js { render 'shared/flash_messages' }
      end
    end

    def not_authorized_to_edit_flash_error
      if current_user
        "You don't have permission to edit that recipe."
      else
        "You must #{view_context.link_to('sign in', new_user_session_path, class: 'link')} before you can edit a recipe."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title,
                                     :description,
                                     :notes,
                                     :acknowledgements,
                                     :preparation_time,
                                     :featured_image,
                                     :user_id,
                                     :jewel_id,
                                     :color_scheme_id,
                                     :cuisine_ids => [],
                                     :meal_type_ids => [],
                                     :diet_ids => [],
                                     :season_ids => [],
                                     :occasion_ids => [],
                                     :pairing_ids => [],
                                     :box_ids => [],
                                     steps_attributes: [:id, :_destroy, :position, :description],
                                     ingredients_attributes: [:id, :_destroy, :position, :title, :amount],)
    end
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_featured_recipe.html.erb
<% cache recipe do %>
  <div class="featured-recipe" style="color: <%= recipe.color %>">
    <div class="col-sm-5 vcenter">
      <%= link_to(recipe, class: 'link--blank') do %>
        <div class="featured-recipe__image-wrapper">
          <%= render 'recipes/gem', recipe: recipe %>
          <%= responsive_image(recipe.featured_image, column_size: 5) if recipe.featured_image.present? %>
        </div>
      <% end %>
    </div><!--
 --><div class="col-sm-5 col-sm-offset-1 vcenter">
      <%= link_to(recipe, class: 'link--blank') do %>
        <%= content_tag(:h2, recipe.title, class: 'featured-recipe__title bangla-regular__large margin-bottom-small') %>
      <% end %>
      <%= link_to("by #{recipe.user.first_name}", user_path(recipe.user), class: 'link--default ib featured-recipe__user patron-thin__large margin-bottom-large') %>
      <%= content_tag(:div, recipe.description, class: 'featured-recipe__description patron-thin__large') %>
    </div>
  </div>
<% end %>

app/views/recipes/_form.html.erb
<%= render 'recipe_color_scheme_styles' %>

<%= simple_form_for(@recipe, html: { class: 'inline-input' }) do |f| %>
  <div class="container">
    <div class="row">

      <div class="user__actions margin-bottom-small">
        <div class="text-left">
          <%= link_to 'Cancel', edit_user_recipes_path(current_user), class: 'button' %>
        </div>
        <div class="text-right">
          <%= f.button :submit, class: 'button', value: 'Save' %>
        </div>
      </div>

      <div class="title">Editing <%= @recipe.title.presence || 'your recipe' %></div>

      <div class="content-column text-center">
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :notes %>
        <%= f.input :acknowledgements %>
        <%= f.input :featured_image, as: :file %>
        <%= f.association :jewel %>
        <%= f.association :color_scheme %>
        <%= f.association :cuisines %>
        <%= f.association :meal_types %>
        <%= f.association :diets %>
        <%= f.association :seasons %>
        <%= f.association :occasions %>
        <%= f.association :pairings, collection: Recipe.all_except(@recipe) %>

        <div class="subtitle">Categories</div>

        <div class="subtitle">Preparation time</div>

        <div class="recipe__preparation-times">
          <div class="recipe__preparation-time-wrapper recipe__preparation-time-wrapper--quick">
            <input type="radio" id="recipe_preparation_time_quick" name="recipe[preparation_time]" value="<%= Recipe.preparation_times.key(0) %>" class="recipe__preparation-time__input" <%= 'checked' if @recipe.preparation_time == Recipe.preparation_times.key(0) %> />
            <label class="recipe__preparation-time__label" for="recipe_preparation_time_quick">
              <%= embedded_svg 'preparation-time-quick', class: 'recipe__preparation-time-icon recipe__preparation-time--quick' %>
              <span class="recipe__preparation-time__label__name">Quick</span>
            </label>
          </div>

          <div class="recipe__preparation-time-wrapper recipe__preparation-time-wrapper--slow">
            <input type="radio" id="recipe_preparation_time_slow" name="recipe[preparation_time]" value="<%= Recipe.preparation_times.key(1) %>" class="recipe__preparation-time__input" <%= 'checked' if @recipe.preparation_time == Recipe.preparation_times.key(1) %> />
            <label class="recipe__preparation-time__label" for="recipe_preparation_time_slow">
              <%= embedded_svg 'preparation-time-quick', class: 'recipe__preparation-time-icon recipe__preparation-time--slow' %>
              <span class="recipe__preparation-time__label__name">Time consuming</span>
            </label>
          </div>
        </div>

        <br>


        <hr class="hr--dotted">
        <br>
        <br>
      </div>

      <div class="col-sm-4">
        <h3 class="subtitle">Ingredients</h3>
        <div data-sortable="true">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add ingredient', f, :ingredients %>
          </div>
        </div>
      </div>
      <div class="col-sm-8">
        <h3 class="subtitle">Procedure</h3>
        <div class="margin-bottom-large" data-sortable="true">
          <%= f.simple_fields_for :steps do |step| %>
            <%= render 'step_fields', f: step %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add step', f, :steps %>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="text-right">
        <%= f.button :submit, class: 'button', value: 'Save' %>
      </div>
    </div>
  </div>


<% end %>

app/views/recipes/_gem.html.erb
<% if recipe.jewel.present? %>
  <div class="recipe__gem text-center">
    <%= image_tag recipe.jewel.image.url %>
  </div>
<% end %>

app/views/recipes/_ingredient.html.erb
<div class="ingredient">
  <%= content_tag(:span, ingredient.amount, class: 'ingredient__amount') %>
  <%= content_tag(:span, ingredient.title, class: 'ingredient__title') %>
</div>

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
  <%= f.input :title %>
  <%= f.input :amount %>
  <%= link_to_remove_association "Remove ingredient", f %>
</div>

app/views/recipes/_recently_uploaded_recipes.html.erb
<% cache cache_key_for(recipes) do %>
  <div class="recently-uploaded-recipes">
    <div class="marquee-wrapper">
      <div class="marquee">
        <% recipes.each do |recipe| %>
          <div class="recently-uploaded-recipes__recipe">
            <%= render 'recipes/gem', recipe: recipe %>
            <%= link_to(recipe.title, recipe_path(recipe), class: 'recently-uploaded-recipes__recipe__title patron-regular__large link--blank') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<% cache recipe do %>
  <div class="recipes-grid__item text-center col-sm-4" style="color: <%= recipe.color %>">
    <%= link_to(recipe, class: 'link--blank display-block') do %>
      <%= render 'recipes/gem', recipe: recipe %>
      <%= content_tag(:h2, recipe.title, class: 'recipes-grid__item__title recipes-grid__item__centered-text bangla-regular__large margin-bottom-medium') %>
      <%= content_tag(:div, "by #{recipe.user.first_name}", class: 'recipes-grid__item__user patron-thin__large') %>
    <% end %>
  </div>

  <% if recipe_counter % 3 == 2 %>
    <div class="clearfix hidden-xs"></div>
  <% end %>
<% end %>

app/views/recipes/_recipe_color_scheme_styles.html.erb
<%# Color scheme unique to this recipe %>
<style type="text/css">
  .link--default {
    background: -webkit-linear-gradient(#fff, #fff),
    -webkit-linear-gradient(#fff, #fff),
    -webkit-linear-gradient(<%= @recipe.color %>, <%= @recipe.color %>);
  }
  .nav--primary__recipe-box-logo:hover {
    fill: <%= @recipe.color %>;
  }
</style>

app/views/recipes/_step.html.erb
<%= content_tag(:li, step.description, class: 'step') %>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields">
  <%= f.input :description %>
  <%= f.input :position, as: :hidden %>
  <%= link_to_remove_association "Remove step", f %>
</div>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<%# Page Meta %>
<%= page_title('All Recipes') %>
<%= page_description("There are #{Recipe.count} recipes on Recipe Box right now, uploaded by #{User.with_uploaded_recipes.count} different users. These are some of the most recent recipes.") %>

<% cache cache_key_for(@recipes) do %>
  <div class="container">
    <div class="row">
      <div class="recipes-grid">
        <%= render partial: 'recipes/recipe', collection: @recipes %>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<% cache [@recipe, @user] do %>

  <%# Page Meta %>
  <%= page_title @recipe.title %>
  <%= page_description("#{@recipe.title} is a recipe by #{@recipe.user.full_name}. It was uploaded on #{full_date(@recipe.created_at)} and appears in #{@recipe.boxes.count} other boxes.") %>

  <%= render 'recipe_color_scheme_styles' %>

  <%# Recipe body %>
  <div class="container">
    <div class="row recipe--show__wrapper" style="color: <%= @recipe.color %>">
      <div class="recipe--show__content col-sm-12">

        <% if users_own_recipe? %>
          <div class="user__actions margin-bottom-small">
            <div class="text-right">
              <%= link_to 'Edit recipe', edit_recipe_path(@recipe), class: 'button' %>
            </div>
          </div>
        <% end %>

        <%= render 'gem', recipe: @recipe %>

        <%= content_tag(:h1, @recipe.title, class: 'display-title') %>

        <div class="row margin-bottom-large">
          <div class="col-sm-5">
            <%= content_tag(:div, class: 'recipe--show__image text-center') do %>
              <%= responsive_image(@recipe.featured_image, column_size: 5) %>
            <% end if @recipe.featured_image.present? %>
          </div>
          <div class="col-sm-5 col-sm-offset-1">
            <%= content_tag(:div, md(@recipe.description), class: 'recipe--show__description') if @recipe.description.present? %>
            <%= content_tag(:div, class: 'recipe--show__intro') do %>
              This is a <%= @recipe.diet_names %> recipe posted by <%= link_to(@user.name, user_path(@user), class: 'link--default') %>.
            <% end %>
          </div>
        </div>

        <% if @recipe.preparation_time.present? %>
          <div class="row">
            <div class="col-sm-12">
              <div class="recipe__preparation-times margin-bottom-large">
                <div class="recipe--show__preparation-time">
                  <%= embedded_svg 'preparation-time-quick', class: 'recipe__preparation-time-icon recipe__preparation-time--quick' %>
                  <div class="recipe__preparation-time__label__name">
                    <%= @recipe.preparation_time.humanize %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>

        <div class="row margin-bottom-large">
          <div class="col-sm-12">
            <div class="text-center">
              <%= link_to 'Save to your box', save_to_box_path, method: :post, remote: true, class: 'button save-to-box-button' %>
              <%= link_to('Print / Save as PDF', '#', class: 'button') %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <h3 class="subtitle">Ingredients</h3>
            <div class="">
              <%= render partial: 'ingredient', collection: @recipe.ingredients %>
            </div>
          </div>
          <div class="col-sm-8">
            <h3 class="subtitle">Procedure</h3>
            <div class=" margin-bottom-large">
              <ol class="list--default">
                <%= render partial: 'step', collection: @recipe.steps %>
              </ol>
            </div>

            <%= content_tag(:div, class: 'recipe--show__notes margin-bottom-large') do %>
              <h3 class="h3 subtitle">Notes</h3>
              <%= @recipe.notes %>
            <% end if @recipe.notes? %>

            <%= content_tag(:div, class: 'recipe--show__acknowledgements margin-bottom-large') do %>
              <h3 class="h3 subtitle">Acknowledgements</h3>
              <%= @recipe.acknowledgements %>
            <% end if @recipe.acknowledgements? %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%# Recipe pairings %>
  <% if @recipe.pairings.any? %>
    <div class="container-fluid">
      <div class="recipe--show__pairings row">
        <div class="recipe--show__pairings__left-column recipe--show__pairings__column text-center col-sm-4">
          <div class="recipe--show__pairings__left-column__inner col-sm-4">
            <div class="patron-regular__large">Suggested<br>pairings</div>
          </div>
        </div>
        <div class="recipe--show__pairings__right-column recipe--show__pairings__column patron-thin__large col-sm-8" <%= "data-carousel" if @pairings.count > 1 %>>
          <%= render partial: 'recipe', collection: @pairings, layout: 'pairing_layout' %>
        </div>
      </div>
    </div>
  <% end %>

<% end %>

<%# Collected by users %>
<% if @recipe.collected? %>
  <% collected_limit = 3 %>
  <% cache @recipe.boxes.first(collected_limit) do %>
    <div class="recipe--show__collected-by patron-regular__medium text-center">
      <div class="container">
        <div class="col-sm-12">
          <h4 class="recipe--show__collected-by__title">This recipe has been collected by</h4>
          <% @recipe.boxes.first(collected_limit).each do |box| %>
            <div class="recipe--show__collected-by__user">
              <span class="recipe--show__collected-by__user__avatar">
                avatar
              </span>
              <%= link_to(box.user.full_name, box.user, class: 'recipe--show__collected-by__user__name') %>
            </div>
          <% end %>
          <%# TODO: Add javascript for this toggle, and fix the link color %>
          <% if @recipe.boxes.count > collected_limit %>
            <div class="recipe--show__collected-by__user__total-wrapper">
              and
              <span class="recipe--show__collected-by__user__total-count link">
                <%= @recipe.boxes.count %> others
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>