config/routes.rb
Rails.application.routes.draw do

  #
  # Public
  #

  get '/soon', to: 'holding_pages#show', as: 'holding_page'

  root to: "home#index"

  # Recipes
  resources :recipes
  post '/recipes/save/:id', to: 'recipes#save_to_box', as: 'save_to_box'
  # get 'recipes', to: 'recipes#index', as: 'recipes'
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'

  # Users
  get   '/users', to: 'users#index', as: 'users'
  get   '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  get   '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  get   '/users/:id/recipes/edit', to: 'users#edit_recipes', as: 'edit_user_recipes'
  get   '/users/:id/saved-recipes/edit', to: 'users#edit_saved_recipes', as: 'edit_user_saved_recipes'

  # Blog / Tumblr feed
  get '/mmmbox', to: 'blog#mmmbox', as: 'tumblr'

  # About
  get '/about', to: 'about#index'
  get '/about/statement', to: 'about#statement'

  # Search
  get 'search', to: 'search#index'


  #
  # Admin
  #

  # Admin dashboard
  get '/admin', to: 'dashboard#index', as: 'admin'
  namespace :admin do
    resources :color_schemes
    resources :jewels
    resources :user_groups
    resources :users
  end


  #
  # Authentication
  #

  get '/signup/confirm/:id', to: 'users#confirm', as: 'confirm_user_registration'
  patch '/signup/confirm/:id', to: 'users#confirm_update'

  devise_for :users, path: '', controllers: { registrations: 'users/registrations' },
                               path_names:  { sign_in: '/login', sign_out: '/logout', sign_up: '/signup' }
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

end

app/views/shared/_flash_messages.html.erb
<% if flash_message.present? %>
  <% modal_id = Digest::MD5.hexdigest(flash_message) %>
  <%= render 'shared/modal', modal_button_text: false, modal_id: modal_id, content: md(flash_message), modal_classes: flash_message_type.to_s %>
  <script>
    (function () {
      var modal = document.getElementById( '<%= modal_id %>' );
      var dlg = new DialogFx( modal );
      dlg.toggle();
    })();
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer--primary">
  <div class="container">
    <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-3">
          <%= link_to(root_path) do %>
            <%= embedded_svg('recipe-box-logo', class: 'recipe-box-logo footer--primary__recipe-box-logo') %>
          <% end %>
        </div>
        <div class="col-sm-3">
          Recipe box<br>
          Community<br>
          <%= link_to('Guidelines', about_path(anchor: 'guidelines')) %>
        </div>
        <div class="col-sm-3">
          <%= link_to('Profile<br>'.html_safe, user_path(current_user)) if current_user %>
          Submit<br>
          <%= login_or_logout_link %>
        </div>
        <div class="col-sm-3">
          Newsletter
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_modal.html.erb
<%# Usage: %>
<%#= render 'shared/modal', modal_button_text: 'Open this guy', modal_id: 'dialog_tester', content: 'This is a tester.', modal_classes: 'success' %>

<% if modal_button_text %>
  <div class="button-wrap">
    <button data-dialog="<%= modal_id %>" class="button"><%= modal_button_text %></button>
  </div>
<% end %>

<div class="dialog <%= modal_classes %>" id="<%= modal_id %>">
  <div class="dialog__overlay"></div>
  <div class="dialog__content">
    <%= content_tag(:h2, content, class: 'dialog__content__title') %>
    <br>
    <button class="button--small" data-dialog-close>Close</button>
  </div>
</div>

app/views/shared/_nav_primary.html.erb
<nav id="nav--primary" class="nav--primary nav--primary--with-logo nav--primary--fixed clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <%= link_to(root_path, class: 'nav--primary--with-logo__home-link') do %>
          <%= embedded_svg('recipe-box-logo', class: 'recipe-box-logo nav--primary__recipe-box-logo') %>
        <% end %>
        <%= render 'shared/nav_primary_list' %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_nav_primary_list.html.erb
<ul class="nav--primary__list">
  <li class="nav--primary__list-item">
    <%= link_to('Recipes', recipes_path, class: nav_class(recipes_path)) %>
  </li>
  <li class="nav--primary__list-item">
    <%= link_to('About', about_path, class: nav_class(about_path)) %>
  </li>
  <li class="nav--primary__list-item">
    <%= link_to('MMMBox', tumblr_path, class: nav_class(tumblr_path)) %>
  </li>
  <li class="nav--primary__list-item">
    <%= link_to('Profile', user_or_login_path, class: nav_class(user_or_login_path)) %>
  </li>
</ul>

app/views/shared/flash_messages.js.erb
$("body").append("<%= escape_javascript( render('shared/flash_messages') ) %>")

App.startFlashTimer(true);