config/routes.rb
Rails.application.routes.draw do

  #
  # Public
  #

  get '/soon', to: 'holding_pages#show', as: 'holding_page'

  root to: "home#index"

  # Recipes
  resources :recipes
  post '/recipes/save/:id', to: 'recipes#save_to_box', as: 'save_to_box'
  # get 'recipes', to: 'recipes#index', as: 'recipes'
  # get 'recipes/:id', to: 'recipes#show', as: 'recipe'

  # Users
  get   '/users', to: 'users#index', as: 'users'
  get   '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  get   '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  get   '/users/:id/recipes/edit', to: 'users#edit_recipes', as: 'edit_user_recipes'
  get   '/users/:id/saved-recipes/edit', to: 'users#edit_saved_recipes', as: 'edit_user_saved_recipes'

  # Blog / Tumblr feed
  get '/mmmbox', to: 'blog#mmmbox', as: 'tumblr'

  # About
  get '/about', to: 'about#index'
  get '/about/statement', to: 'about#statement'

  # Search
  get 'search', to: 'search#index'


  #
  # Admin
  #

  # Admin dashboard
  get '/admin', to: 'dashboard#index', as: 'admin'
  namespace :admin do
    resources :color_schemes
    resources :jewels
    resources :user_groups
    resources :users
  end


  #
  # Authentication
  #

  get '/signup/confirm/:id', to: 'users#confirm', as: 'confirm_user_registration'
  patch '/signup/confirm/:id', to: 'users#confirm_update'

  devise_for :users, path: '', controllers: { registrations: 'users/registrations' },
                               path_names:  { sign_in: '/login', sign_out: '/logout', sign_up: '/signup' }
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    skip_authorization
  end

  def statement
    skip_authorization
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 bangla-regular__large margin-bottom-huge no-last-p-margin">
      <p>Recipe Box is a space designed to preserve the warmth of cooking. Focusing on style and wholistic ingredients, Recipe Box is a tool that enhances the cooking experience, and captures the spirit of each uploaded recipe. <%= link_to('Read the full statement', about_statement_path, class: 'link--default') %>.</p>
    </div>
    <div class="col-sm-12 text-center margin-bottom-huge">
      <%= image_tag('recipe-box-kale-squash-800.jpg', width: 400, height: 295) %>
    </div>
    <div class="col-sm-12 text-center margin-bottom-medium patron-medium__medium" id="guidelines">Community Guidelines</div>
    <div class="col-sm-10 col-sm-offset-1 text-center margin-bottom-large patron-thin__large">
      Initially, Recipe Box was created to exclusively house vegetarian recipes. While the project is no longer restricted to herbivores, the content should be health based. To maintain the projects goals, please adhere to the following guidelines:
    </div>
    <div class="col-sm-8 col-sm-offset-2 patron-thin__medium margin-bottom-huge">
      <ol class="list--default">
        <li>Avoid recipes with artificial ingredients.</li>
        <li>Avoid recipes that are blatantly unhealthy (i.e Fried Twinkie glazed with melted Jolly Ranchers)</li>
        <li>When transcribing a recipe, write it as though you are telling it to a friend. Use your favorite descriptors but be sure that the procedure is easily understood</li>
        <li>If you are copying a recipe from another source, please re-write it in your own words and credit it in the appropriate field on the recipe page.</li>
      </ol>
    </div>
    <div class="col-sm-12 text-center margin-bottom-medium patron-medium__medium">News</div>
    <div class="col-sm-8 col-sm-offset-2 patron-thin__medium margin-bottom-large text-center">
      Any recent news will be placed here.
    </div>
  </div>
</div>

app/views/about/statement.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 patron-thin__medium">
      <p>Recipe Box long statement lorem ipsum dolor sit amet, consectetur adipiscing elit. In at elementum ante. Sed consectetur risus dui, eget finibus leo congue eget. In venenatis facilisis leo nec placerat. Proin aliquet vestibulum arcu in ultrices. Duis elit turpis, fringilla nec malesuada vel, feugiat vel enim. Vivamus sed tellus eget felis convallis iaculis convallis vitae est. Nam neque arcu, iaculis eget elementum ac, mattis id tortor. Pellentesque dapibus velit diam, convallis rutrum nibh lobortis placerat. Pellentesque iaculis velit at interdum dictum. Etiam dui lacus, faucibus vitae pulvinar eu, scelerisque dignissim odio.</p>
      <p>Aliquam et vehicula est. Curabitur non elit mollis, varius lorem elementum, sagittis lorem. Nulla aliquam erat nisi. Cras non imperdiet lectus. In nibh nulla, eleifend ultrices ultricies ornare, porttitor et eros. Pellentesque cursus tellus vitae lectus pretium accumsan. Vivamus magna lacus, pulvinar malesuada sollicitudin quis, hendrerit sit amet dui. Mauris in malesuada neque, vitae tincidunt erat. Quisque rhoncus elit ligula. Ut pulvinar ut tortor at finibus. Vestibulum commodo vel libero a bibendum. Sed fringilla quis erat id tempus. Phasellus rhoncus erat id blandit pulvinar. Vivamus vel nisl non est interdum lobortis eu eget sem.</p>
      <p>Fusce ac tristique dolor. Donec non nisl a velit fermentum vehicula. Nunc sed tellus justo. Vivamus aliquet ultricies leo sit amet euismod. Ut dapibus ex dui, non tincidunt magna posuere eu. Morbi ullamcorper condimentum arcu, at vulputate ante mollis non. In hendrerit placerat risus id volutpat. Aliquam erat volutpat. Cras faucibus posuere nulla non faucibus. Suspendisse et aliquet diam.</p>
      <p>Nunc varius, orci eu mollis condimentum, nisi tortor aliquam tortor, ac finibus purus dolor non justo. Duis semper sapien a efficitur congue. Vivamus quis ligula turpis. Etiam sit amet velit posuere, pellentesque magna et, scelerisque diam. Proin consequat dignissim dapibus. Cras et ipsum quis ipsum hendrerit efficitur. Sed laoreet ante eget sagittis fringilla. Curabitur sagittis justo nec urna euismod, nec tincidunt elit dapibus. Cras vitae purus maximus, dapibus tortor vel, aliquet magna. Pellentesque dui sem, varius ac purus ac, venenatis dapibus velit. Quisque ac sapien vitae neque vestibulum aliquam.</p>
      <p>Aenean posuere tincidunt ipsum, non imperdiet justo vehicula eu. Fusce pulvinar ipsum eget felis vehicula, non blandit arcu tincidunt. Aliquam tristique sapien at feugiat eleifend. Suspendisse malesuada mi et ex vestibulum, at hendrerit odio tempus. Quisque congue rhoncus leo sit amet fermentum. Sed imperdiet, ligula sit amet malesuada tincidunt, enim sem elementum nisi, luctus porta lorem sem at eros. Curabitur imperdiet viverra ultrices. Donec vitae blandit ante, ac commodo velit.</p>
    </div>
  </div>
</div>